### LMS 쥬피터에서 작성한 코드입니다.

### 라이브러리 불러오기

In [11]:
import numpy as np
import os
import face_recognition
from PIL import Image

### 모든 사진들을 얼굴 영역만 crop하는 함수 만들기

In [ ]:
def all_in_one(image_path): 
    get_cropped_face(image_path) 
    face = get_cropped_face(image_path)
    pillow_image = Image.fromarray(face)   
    pillow_image.save(path_to_save)
    
    return print("done")

In [ ]:
image_path = os.getenv('HOME')+'/aiffel/project/first-repository/aiffelthon_warmtone/공효진.jpg'
path_to_save = os.getenv('HOME')+'/aiffel/project/first-repository/aiffelthon_warmtone/get_cropped_face/공효진.jpg'

In [ ]:
all_in_one(image_path)

### 위와 같은 방법으로 웜톤 50장, 쿨톤 50장을 crop한 이미지들 저장 완료
### 구글 드라이브에 get_cropped_face 폴더로 업로드 

### 이미지에 붙일 0과 1로 된 labels 만들기 

In [1]:
labels = np.zeros(100)
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
labels[50:] = 1

In [3]:
labels
# 웜톤이 0 쿨톤이 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 웜톤 crop한 이미지들 file list 불러오기

In [8]:
dir_path_w = os.getenv('HOME')+'/aiffel/project/first-repository/aiffelthon_warmtone/get_cropped_face' # 디렉토리 경로
file_list_w = os.listdir(dir_path_w)

file_list_w

['유인나.jpg',
 '정유미.jpg',
 '솔빈.jpg',
 '화사.jpg',
 '신세경.jpg',
 '박시연.jpg',
 '윤아.jpg',
 '수애.jpg',
 '채수빈.jpg',
 '이성경.jpg',
 '박정아.jpg',
 '탕웨이.jpg',
 '조이.jpg',
 '전지현.jpg',
 '효린.jpeg',
 '로제.jpg',
 '리사.jpg',
 '공효진.jpg',
 '웬디.jpg',
 '한효주.jpg',
 '쯔위.jpg',
 '한지민.jpg',
 '윤은혜.jpg',
 '유진.jpg',
 '설현.jpg',
 '.ipynb_checkpoints',
 '이민정.jpg',
 '혜리.jpg',
 '이효리.jpg',
 '송혜교.jpg',
 '김유정.jpg',
 '한예슬.jpg',
 '박신혜.jpg',
 '서현.jpeg',
 '하연수.jpg',
 '문정원.jpg',
 '사나.jpg',
 '송지아.jpg',
 '유빈.jpg',
 '김효진.jpg',
 '박민영.jpg',
 '아이유.jpg',
 '장나라.jpg',
 '박보영.jpg',
 '제시.jpg',
 '한소희.jpg',
 '문가영.jpg',
 '제니.jpg',
 '민효린.jpg',
 '한선화.jpg',
 '수지.jpg']

### 쿨톤 crop한 이미지들 file list 불러오기

In [9]:
dir_path_c = os.getenv('HOME')+'/aiffel/project/first-repository/aiffelthon_cooltone/get_cropped_face' # 디렉토리 경로
file_list_c = os.listdir(dir_path_c)

file_list_c

['채영.jpeg',
 '김새롬.jpg',
 '이영애.jpg',
 '서현진.jpg',
 '김정민.jpg',
 '이하늬.jpg',
 '손예진.jpg',
 '티파니.jpg',
 '송윤아.jpg',
 '이유비.jpg',
 '고현정.jpg',
 '유나.jpg',
 '엄지.jpg',
 '하니.jpg',
 '정은채.jpg',
 '손나은.jpg',
 '문채원.jpg',
 '카리나.jpg',
 '임지연.jpg',
 '이영지.jpg',
 '주결경.jpg',
 '판빙빙.jpeg',
 '김옥빈.jpg',
 '나연.jpg',
 '박은빈.jpg',
 '김소연.jpg',
 '김혜수.jpg',
 '유진.jpg',
 '이은지.jpg',
 '류진.jpg',
 '혜림.jpg',
 '아이린.jpg',
 '정수정.jpg',
 '이나영.jpg',
 '고아라.jpg',
 '찬미.jpg',
 '김태리.jpg',
 '선우선.jpg',
 '지수.jpg',
 '유리.jpg',
 '한가인.jpg',
 '김사랑.jpg',
 '태연.jpg',
 '김고은.jpg',
 '현아.jpg',
 '정채연.jpeg',
 '서예지.jpg',
 '장원영.jpg',
 '청하.jpg',
 '미미.jpg']

### 각 이미지들의 array 값과 labels을 매칭

### crop한 웜톤 이미지들을 file_list_w에서 하나씩 불러와 array로 바꿔 image_arrays_w 빈 리스트에 저장

In [12]:
# 이미지 배열을 저장할 빈 리스트를 생성합니다.
image_arrays_w = []

for file_name in file_list_w:
    # .ipynb_checkpoints와 같은 불필요한 파일을 건너뛰기 위한 조건문
    if file_name.endswith(('.jpg', '.jpeg')):
        # 파일 경로를 생성합니다.
        img_path = os.path.join(dir_path_w, file_name)
        # 이미지를 열고 numpy 배열로 변환합니다.
        img = Image.open(img_path)
        img_array = np.array(img)
        # 배열을 리스트에 추가합니다.
        image_arrays_w.append(img_array)

# 결과를 확인합니다.
for img_arr in image_arrays_w:
    print(img_arr)

[[[162  78 156]
  [163  79 157]
  [164  80 158]
  ...
  [ 64  34  24]
  [ 60  31  23]
  [ 62  33  25]]

 [[163  79 157]
  [164  80 158]
  [165  81 159]
  ...
  [ 61  31  21]
  [ 55  26  18]
  [ 56  27  19]]

 [[163  79 157]
  [164  80 158]
  [165  81 159]
  ...
  [ 58  28  18]
  [ 52  24  13]
  [ 52  23  15]]

 ...

 [[215 217 238]
  [215 217 238]
  [215 217 238]
  ...
  [175 132 115]
  [153 110  93]
  [144 101  84]]

 [[215 217 238]
  [215 217 238]
  [215 217 238]
  ...
  [169 126 109]
  [154 111  94]
  [152 109  92]]

 [[215 217 238]
  [215 217 238]
  [215 217 238]
  ...
  [169 126 109]
  [158 115  98]
  [161 118 101]]]
[[[222 212 202]
  [218 208 198]
  [234 224 214]
  ...
  [ 41  41  33]
  [ 36  36  28]
  [ 37  37  29]]

 [[221 211 201]
  [220 210 200]
  [222 212 202]
  ...
  [ 41  41  33]
  [ 36  36  28]
  [ 38  38  30]]

 [[219 211 200]
  [224 214 204]
  [208 198 188]
  ...
  [ 42  42  34]
  [ 34  34  26]
  [ 36  36  28]]

 ...

 [[122 119 114]
  [179 176 171]
  [195 192 187]
  ..

In [13]:
len(image_arrays_w)

50

### crop한 쿨톤 이미지들을 file_list_c에서 하나씩 불러와 array로 바꿔 image_arrays_c 빈 리스트에 저장

In [14]:
# 이미지 배열을 저장할 빈 리스트를 생성합니다.
image_arrays_c = []

for file_name in file_list_c:
    # .ipynb_checkpoints와 같은 불필요한 파일을 건너뛰기 위한 조건문
    if file_name.endswith(('.jpg', '.jpeg')):
        # 파일 경로를 생성합니다.
        img_path = os.path.join(dir_path_c, file_name)
        # 이미지를 열고 numpy 배열로 변환합니다.
        img = Image.open(img_path)
        img_array = np.array(img)
        # 배열을 리스트에 추가합니다.
        image_arrays_c.append(img_array)

# 결과를 확인합니다.
for img_arr in image_arrays_c:
    print(img_arr)

[[[ 53  53  55]
  [ 50  50  52]
  [ 48  47  52]
  ...
  [ 64  63  68]
  [ 93  92  97]
  [ 72  71  76]]

 [[ 52  52  54]
  [ 50  50  52]
  [ 48  47  52]
  ...
  [ 68  67  72]
  [ 86  85  90]
  [ 80  79  84]]

 [[ 52  52  54]
  [ 50  50  52]
  [ 47  46  51]
  ...
  [ 74  73  78]
  [ 76  75  80]
  [ 84  83  88]]

 ...

 [[ 45  44  50]
  [ 46  45  51]
  [ 47  46  52]
  ...
  [172 111  90]
  [169 108  89]
  [161 100  81]]

 [[ 39  38  44]
  [ 42  41  47]
  [ 42  41  47]
  ...
  [165 104  83]
  [159 101  81]
  [155  97  77]]

 [[ 39  38  44]
  [ 42  41  47]
  [ 42  41  47]
  ...
  [161 103  81]
  [156  98  78]
  [153  95  75]]]
[[[127 152 156]
  [125 150 154]
  [112 140 144]
  ...
  [ 47  45  59]
  [ 58  56  70]
  [ 66  70  79]]

 [[124 149 153]
  [128 153 157]
  [130 158 162]
  ...
  [ 52  50  64]
  [ 64  62  76]
  [ 65  69  78]]

 [[126 151 155]
  [132 157 161]
  [141 169 173]
  ...
  [ 47  45  59]
  [ 54  52  66]
  [ 50  54  65]]

 ...

 [[191 154 135]
  [191 154 135]
  [191 154 135]
  ..

In [15]:
len(image_arrays_c)

50

### 웜톤, 쿨톤 각각 50장씩 array로 변환하기 완료

### 웜톤, 쿨톤 array들을 한 리스트에 합치기

In [16]:
image_arrays_w_c = image_arrays_w + image_arrays_c
# w(웜톤) + c(쿨톤) 순서로 붙였기에 
# 라벨도 앞에오는 0이 웜톤, 1이 쿨톤

In [17]:
len(image_arrays_w_c)

100

### 수빈님이 작성해주신 train, val, test 데이터셋 나누기 코드로 시도해 보았으나 
### image_arrays_w_c가 리스트로 되어있어 train_data = np.zeros((train_size, *image_arrays_w_c.shape[1:])) 부분에서 에러가 남
### 에러메세지: AttributeError: 'list' object has no attribute 'shape'


### crop한 이미지들의 크기를 확인해보니 얼굴영역이지만 다 달라 이미지 사이즈를 통일하기로 함

In [18]:
# 각 이미지 데이터 array들의 크기 확인
for img_arr in image_arrays_w_c:
    print(img_arr.shape)

(223, 223, 3)
(186, 186, 3)
(186, 186, 3)
(223, 223, 3)
(463, 462, 3)
(385, 386, 3)
(321, 321, 3)
(321, 321, 3)
(185, 186, 3)
(321, 321, 3)
(321, 321, 3)
(155, 155, 3)
(223, 223, 3)
(267, 268, 3)
(223, 223, 3)
(186, 185, 3)
(321, 321, 3)
(268, 267, 3)
(321, 321, 3)
(223, 223, 3)
(186, 186, 3)
(223, 223, 3)
(223, 223, 3)
(267, 268, 3)
(463, 462, 3)
(267, 268, 3)
(223, 223, 3)
(129, 129, 3)
(186, 185, 3)
(186, 185, 3)
(223, 223, 3)
(223, 223, 3)
(666, 666, 3)
(186, 186, 3)
(223, 223, 3)
(186, 186, 3)
(107, 107, 3)
(223, 223, 3)
(155, 155, 3)
(385, 385, 3)
(268, 268, 3)
(463, 463, 3)
(223, 223, 3)
(90, 90, 3)
(321, 321, 3)
(666, 666, 3)
(267, 268, 3)
(186, 186, 3)
(321, 321, 3)
(108, 107, 3)
(186, 185, 3)
(321, 321, 3)
(268, 268, 3)
(185, 186, 3)
(186, 185, 3)
(223, 223, 3)
(385, 385, 3)
(186, 186, 3)
(268, 268, 3)
(155, 155, 3)
(267, 268, 3)
(385, 385, 3)
(185, 185, 3)
(321, 321, 3)
(385, 385, 3)
(186, 185, 3)
(217, 223, 3)
(385, 385, 3)
(107, 107, 3)
(223, 223, 3)
(186, 186, 3)
(186, 18

In [ ]:
# 이미지 크기가 다 다름

### height = 200, width = 200로 통일하기로 함 

In [19]:
image_arrays_w_c_resized_rgb = []

for img_arr in image_arrays_w_c:
    img = Image.fromarray(img_arr)
    resized_img = img.resize((200, 200)) # (통일할 높이, 통일할 너비)
    rgb_img = resized_img.convert('RGB')
    img_arr_resized_rgb = np.array(rgb_img)
    image_arrays_w_c_resized_rgb.append(img_arr_resized_rgb)

image_arrays_w_c_np = np.array(image_arrays_w_c_resized_rgb)

In [21]:
type(image_arrays_w_c_np)

numpy.ndarray

In [22]:
# 사이즈 재확인
for img_arr in image_arrays_w_c_np:
    print(img_arr.shape)

(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 200, 3)
(200, 

In [ ]:
# 통일됨

### KNN은 input data를 2차원 배열 형태로 넣어야 한다고 합니다.
KNeighborsClassifier와 같은 scikit-learn의 기계 학습 모델들은 2차원 배열 형태의 입력 데이터를 기대합니다.      
현재 이미지 데이터는 3차원 (높이, 너비, 컬러 채널) 또는 그 이상의 차원을 가지고 있을 것입니다. 따라서 이를 2차원으로 재구성해야 합니다.     
이미지 데이터를 2차원으로 변환하는 가장 일반적인 방법은 각 이미지를 단일 행으로 "평탄화"하는 것입니다.      
각 픽셀의 색상 채널 값을 연속적인 열로 나열하여 이미지를 단일 행의 2D 배열로 변환합니다.       
이렇게 하면 각 행은 하나의 이미지를 나타내며, 행의 각 열은 이미지의 각 픽셀을 나타냅니다.

In [23]:
# 이미지 데이터를 2차원으로 재구성
n_images, height, width, channels = image_arrays_w_c_np.shape
image_arrays_w_c_2d = image_arrays_w_c_np.reshape(n_images, height * width * channels)

In [24]:
image_arrays_w_c_2d.shape

(100, 120000)

### train, test data로 나누기 위해 임의의 index 생성

In [25]:
np.random.seed(42)
index = np.arange(100)
np.random.shuffle(index)

In [26]:
print(index)

[83 53 70 45 44 39 22 80 10  0 18 30 73 33 90  4 76 77 12 31 55 88 26 42
 69 15 40 96  9 72 11 47 85 28 93  5 66 65 35 16 49 34  7 95 27 19 81 25
 62 13 24  3 17 38  8 78  6 64 36 89 56 99 54 43 50 67 46 68 61 97 79 41
 58 48 98 57 75 32 94 59 63 84 37 29  1 52 21  2 23 87 91 74 86 82 20 60
 71 14 92 51]


In [ ]:
### train_data는 70개, test_data는 30개(총 100개)

In [27]:
train_input = image_arrays_w_c_2d[index[:70]]
train_target = labels[index[:70]]

In [28]:
print(image_arrays_w_c_2d[83], train_input[0])

[17  9  6 ...  9  9  9] [17  9  6 ...  9  9  9]


In [ ]:
# 원본데이터와 비교시 동일한 것 확인

In [29]:
test_input = image_arrays_w_c_2d[index[70:]]
test_target = labels[index[70:]]

In [ ]:
### KNN 모델 학습

In [30]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()

In [31]:
kn.fit(train_input, train_target)

KNeighborsClassifier()

In [32]:
kn.score(test_input, test_target)

0.5

In [33]:
kn.predict(test_input)

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.])

In [34]:
test_target

array([1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.])

### knn 모델의 매개변수 n_neighbors를 조정해 봄

In [35]:
kn10 = KNeighborsClassifier(n_neighbors=10)
kn10.fit(train_input, train_target)
kn10.score(test_input, test_target)

0.4

In [37]:
kn49 = KNeighborsClassifier(n_neighbors=49)
kn49.fit(train_input, train_target)
kn49.score(test_input, test_target)

0.36666666666666664

## 아아 왜 KNN인데 최대 정확도가 0.5라니 왜 그런걸까요ㅠㅠ 후엥